graph TD;
    sbc["Klipper Host (Raspberry Pi)"]
    transceiver[SN65HVD230 CAN transceiver]
    wago[Wago locking lever]
    t0[primary tool]
    t1[secondary tool]
    t2[tertiary tool]
    primary[primary mcu]

    sbc <--USB--> primary <--dupont--> transceiver
    transceiver <--> wago <--> t0 & t1 & t2