graph TD;
    sbc["Klipper Host (Raspberry Pi)"]
    t0[tool]
    t1[tool]
    t2[tool]
    primary["primary mcu with onboard transciever"]

    sbc <--USB--> primary <--molex microfit--> t0 
    t0 <--molex microfit--> t1 <--molex microfit--> t2