graph TD;
    sbc["Klipper Host (Raspberry Pi)"]
    t0[tool]
    t1[tool]
    t2[tool]
    primary0["primary mcu with onboard transciever"]
    primary1["primary mcu with onboard transciever"]
    primary2["primary mcu with onboard transciever"]

    sbc <--USB---> primary0 <--molex microfit--> t0 
    sbc <--USB---> primary1 <--molex microfit--> t1 
    sbc <--USB---> primary2 <--molex microfit--> t2 