graph TD;
    sbc["Klipper Host (Raspberry Pi)"]
    u2c((U2C board))
    t0[primary tool]
    t1[secondary tool]
    t2[tertiary tool]
    primary[primary mcu]

    t0 <--Screw terminal--> u2c
    sbc <--USB--> u2c 
    u2c <--Molex Mircofit cable--> t1 
    u2c <--Molex Minifit cable-->  t2 
    u2c <-- USB with CAN signal--> primary